const IS_DEVELOP = process.env.NODE_ENV === 'development';

export const testToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE3MTA4NDAxNDQsImV4cCI6MTcxMDg2ODk0NCwiYXVkIjoiYXBpLnBsYXRmb3JtLnBhZ29wYS5pdCIsImlzcyI6Imh0dHBzOi8vYXBpLmRldi5wbGF0Zm9ybS5wYWdvcGEuaXQiLCJ1aWQiOiI1MDk2ZTRjNi0yNWExLTQ1ZDUtOWJkZi0yZmI5NzRhN2MxYzgiLCJuYW1lIjoiQW5zZWxtbyIsImZhbWlseV9uYW1lIjoiU2FydG9yaSIsImVtYWlsIjoiZnVyaW92aXRhbGVAbWFydGluby5pdCIsIm9yZ19pZCI6IjViNzEzMGZiLWRiZTEtNGUzYi1iMDJiLTJhOWNmYWY1NDYwMiIsIm9yZ192YXQiOiI5OTk5OTAwMDAxMSIsIm9yZ19wYXJ0eV9yb2xlIjoiTUFOQUdFUiIsIm9yZ19yb2xlIjoiYWRtaW4ifQ.A1O5xxkCa3FrflHrPohumya0bwzHRTf9K_w3N2g5vbhElvMDvSbxzBoY872GVYaxr106dCAnbjM70sGspHdnNgfUpfKRd1w3qfiLiUlnRpf3sDe4I7d5sppdMOTr1GGIbBcIt1NHUZ5zSyKYFxx3HMm8pLED_uFbNGS8HSCBzNMl8CqqzOdicfwENEP2gMaAfxpCq3MDmaj5ZNLpkpM9AclAsWJMDAC57l5V1x71OwENxLSr8vlAAAQelmzLWAnBTQbKlc4il_8Xv-3Cpx1RxiToaQiiMNmdv4XVSI3iDq5VBf5lUSk2YAx3kuEPiooLM64SndgCg-kzZ1irwdz8NQ';
export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = false;

export const LOADING_TASK_LOGIN_CHECK = 'LOGIN_CHECK';
export const LOADING_TASK_SEARCH_PARTIES = 'SEARCH_PARTIES';
export const LOADING_TASK_SEARCH_PARTY = 'SEARCH_PARTY';
export const LOADING_FEATURE_FLAGS = 'LOADING_FEATURE_FLAGS';
export const LOADING_TASK_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOADING_TASK_API_KEY_GENERATION = 'API_KEY_GENERATION';
export const LOADING_TASK_PSP_AVAILABLE = 'PSP_AVAILABLE';
export const LOADING_TASK_CHANNELS_LIST = 'CHANNELS_LIST';
export const LOADING_TASK_CHANNEL_ADD_EDIT = 'CHANNEL_ADD_EDIT';
export const LOADING_TASK_CHANNEL_DETAIL = 'CHANNEL_DETAIL';
export const LOADING_TASK_CHANNEL_PSP_TABLE = 'CHANNEL_PSP_TABLE';
export const LOADING_TASK_STATION_ADD_EDIT = 'STATIONS_ADD_EDIT';
export const LOADING_TASK_STATION_DETAILS = 'STATION_DETAILS';
export const LOADING_TASK_STATION_DETAILS_WRAPPER = 'STATION_DETAILS_WRAPPER';
export const LOADING_TASK_STATION_EC_TABLE = 'STATION_EC_TABLE';
export const LOADING_TASK_EC_AVAILABLE = 'EC_AVAILABLE';
export const LOADING_TASK_SEGREGATION_CODES_AVAILABLE = 'EC_AVAILABLE';
export const LOADING_TASK_GENERATION_STATION_CODE = 'GENERATE_STATION_CODE';
export const LOADING_TASK_RETRIEVE_STATIONS = 'RETRIEVE_STATIONS';
export const LOADING_TASK_NODE_SIGN_IN_PSP = 'NODE_SING_IN_PSP';
export const LOADING_TASK_NODE_SIGN_IN_EC = 'NODE_SING_IN_EC';
export const LOADING_TASK_DASHBOARD_GET_EC_PSP_DETAILS = 'DASHBOARD_GET_EC_PSP_DETAILS';
export const LOADING_TASK_CHANNEL_WRAPPER_DETAIL = 'CHANNEL_WRAPPER_DETAIL';
export const LOADING_TASK_PAYMENT_TYPE = 'LOADING_TASK_PAYMENT_TYPE';
export const LOADING_TASK_IBAN_TABLE = 'LOADING_TASK_IBAN_TABLE';
export const LOADING_TASK_IBAN_STAND_IN_AND_CUP = 'LOADING_TASK_IBAN_STAND_IN_AND_CUP';
export const LOADING_TASK_GET_IBAN = 'LOADING_TASK_GET_IBAN';
export const LOADING_TASK_CREATE_IBAN = 'LOADING_TASK_CREATE_IBAN';
export const LOADING_TASK_DELETE_IBAN = 'LOADING_TASK_DELETE_IBAN';
export const LOADING_TASK_COMMISSION_BUNDLE_LIST = 'LOADING_TASK_COMMISSION_BUNDLE_LIST';
export const LOADING_TASK_COMMISSION_BUNDLE_DETAIL = 'LOADING_TASK_COMMISSION_BUNDLE_DETAIL';
export const LOADING_TASK_COMMISSION_BUNDLE_SELECT_DATAS =
    'LOADING_TASK_COMMISSION_BUNDLE_SELECT_DATAS';
export const LOADING_TASK_CREATING_COMMISSION_BUNDLE = 'LOADING_TASK_CREATING_COMMISSION_BUNDLE';
export const LOADING_TASK_GET_CHANNELS_IDS = 'LOADING_TASK_GET_CHANNELS_IDS';
export const LOADING_TASK_OPERATION_TABLE_LIST = 'LOADING_TASK_OPERATION_TABLE_LIST';
export const LOADING_TASK_CREATE_OPERATION_TABLE = 'LOADING_TASK_CREATE_OPERATION_TABLE';
export const LOADING_TASK_CI_DELEGATIONS_LIST = 'LOADING_TASK_CI_DELEGATIONS_LIST';
export const INSTITUTIONS_PSP_CHANNEL_TYPES = ["PSP"];
export const INSTITUTIONS_EC_STATION_TYPES = ["PA", "GSP", "SCP", "PG"];
export const DISALLOWED_PAYMENT_TYPES = ["PO", "OBEP", "JIF", "BP", "BBT", "AD"];

