const IS_DEVELOP = process.env.NODE_ENV === 'development';

export const testToken = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJpYXQiOjE2Nzc4NDAzODksImF1ZCI6ImFwaS5wbGF0Zm9ybS5wYWdvcGEuaXQiLCJpc3MiOiJodHRwczovL2FwaS5kZXYucGxhdGZvcm0ucGFnb3BhLml0IiwidWlkIjoiNTA5NmU0YzYtMjVhMS00NWQ1LTliZGYtMmZiOTc0YTdjMWM4IiwibmFtZSI6IkFuc2VsbW8iLCJmYW1pbHlfbmFtZSI6IlNhcnRvcmkiLCJlbWFpbCI6ImZ1cmlvdml0YWxlQG1hcnRpbm8uaXQiLCJvcmdfaWQiOiIyZDZmZTNjNi01NjU2LTQzYzgtYWZkNC1jY2YyYmIzNTJjZWMiLCJvcmdfdmF0IjoiMTQ4NDcyNDEwMDgiLCJvcmdfcGFydHlfcm9sZSI6IkRFTEVHQVRFIiwib3JnX3JvbGUiOiJhZG1pbiJ9.Nyz5_68eoZfAFBb3zkAbluxZuxwDeuIGesQ5Le3aABbG6r5H6Bbbzmreu696H1faWshWp_DMj_mxRxUJW7ugBnZ1voEiEYxqgRgr8AQz63UK5lPduskY1mZvGgtKQUn_pMGERypqZUv7HTHSO5iJ-gXr_HJ5B_svhgOQbSTs0duT6kksdgUzF6TZw97mQbNNCAuPXJSxQ67dHNuwmwUXcGfxnkmlGkRuR8kFj-jr0K6444-fTB4R1BtnkuhgT1smOysR6hVQkZJdWY-6vhPrcwahaQ4ehsbeylf9aVO1pBgz_p1IsePzCwi_B1SvXxpPI81RVyjYJ1mdEuQSbRWEWQ';

export const MOCK_USER = IS_DEVELOP;
export const LOG_REDUX_ACTIONS = false;

export const LOADING_TASK_LOGIN_CHECK = 'LOGIN_CHECK';
export const LOADING_TASK_SEARCH_PARTIES = 'SEARCH_PARTIES';
export const LOADING_TASK_SEARCH_PARTY = 'SEARCH_PARTY';
export const LOADING_TASK_SEARCH_PRODUCTS = 'SEARCH_PRODUCTS';
export const LOADING_TASK_API_KEY_GENERATION = 'API_KEY_GENERATION';
export const LOADING_TASK_PSP_AVAILABLE = 'PSP_AVAILABLE';
export const LOADING_TASK_CHANNELS_LIST = 'CHANNELS_LIST';
export const LOADING_TASK_CHANNEL_ADD_EDIT = 'CHANNEL_ADD_EDIT';
export const LOADING_TASK_CHANNEL_DETAIL = 'CHANNEL_DETAIL';
export const LOADING_TASK_CHANNEL_PSP_TABLE = 'CHANNEL_PSP_TABLE';
export const LOADING_TASK_STATION_ADD_EDIT = 'STATIONS_ADD_EDIT';
export const LOADING_TASK_STATION_DETAILS = 'STATION_DETAILS';
export const LOADING_TASK_STATION_DETAILS_WRAPPER = 'STATION_DETAILS_WRAPPER';
export const LOADING_TASK_STATION_EC_TABLE = 'STATION_EC_TABLE';
export const LOADING_TASK_EC_AVAILABLE = 'EC_AVAILABLE';
export const LOADING_TASK_SEGREGATION_CODES_AVAILABLE = 'EC_AVAILABLE';
export const LOADING_TASK_GENERATION_STATION_CODE = 'GENERATE_STATION_CODE';
export const LOADING_TASK_RETRIEVE_STATIONS = 'RETRIEVE_STATIONS';
export const LOADING_TASK_NODE_SIGN_IN_PSP = 'NODE_SING_IN_PSP';
export const LOADING_TASK_NODE_SIGN_IN_EC = 'NODE_SING_IN_EC';
export const LOADING_TASK_DASHBOARD_GET_EC_PSP_DETAILS = 'DASHBOARD_GET_EC_PSP_DETAILS';
export const LOADING_TASK_CHANNEL_WRAPPER_DETAIL = 'CHANNEL_WRAPPER_DETAIL';
export const LOADING_TASK_PAYMENT_TYPE = 'LOADING_TASK_PAYMENT_TYPE';
export const LOADING_TASK_IBAN_TABLE = 'LOADING_TASK_IBAN_TABLE';
export const LOADING_TASK_IBAN_STAND_IN_AND_CUP = 'LOADING_TASK_IBAN_STAND_IN_AND_CUP';
export const LOADING_TASK_GET_IBAN = 'LOADING_TASK_GET_IBAN';
export const LOADING_TASK_CREATE_IBAN = 'LOADING_TASK_CREATE_IBAN';
export const LOADING_TASK_DELETE_IBAN = 'LOADING_TASK_DELETE_IBAN';
export const LOADING_TASK_COMMISSION_PACKAGE_DETAIL = 'LOADING_TASK_COMMISSION_PACKAGE_DETAIL';
export const LOADING_TASK_COMMISSION_PACKAGE_SELECT_DATAS =
  'LOADING_TASK_COMMISSION_PACKAGE_SELECT_DATAS';
export const LOADING_TASK_CREATING_COMMISSION_PACKAGE = 'LOADING_TASK_CREATING_COMMISSION_PACKAGE';
export const LOADING_TASK_OPERATION_TABLE_LIST = 'LOADING_TASK_OPERATION_TABLE_LIST';
export const LOADING_TASK_CREATE_OPERATION_TABLE = 'LOADING_TASK_CREATE_OPERATION_TABLE';
