name: Code Review

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
  push:
    branches:
      - main

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

env:
  PROJECT_KEY: pagopa_pagopa-selfcare-frontend

permissions:
  id-token: write
  contents: read
  deployments: write

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    environment: dev
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Build
        run: |
          export REACT_APP_ENV='${{ needs.setup.outputs.environment }}'
          export INLINE_RUNTIME_CHUNK='false'

          export REACT_APP_URL_FE_LOGIN='${{ vars.SELFCARE_HOST_FE }}/auth/login'
          export REACT_APP_URL_FE_LOGOUT='${{ vars.SELFCARE_HOST_FE }}/auth/logout'
          export REACT_APP_URL_FE_LANDING='${{ vars.SELFCARE_HOST_FE }}/auth/logout'
          export REACT_APP_URL_FE_ASSISTANCE='${{ vars.SELFCARE_HOST_FE }}/assistenza'
          export REACT_APP_URL_FE_SELFCARE='${{ vars.SELFCARE_HOST_FE }}/dashboard/'
          export REACT_APP_URL_FE_TOKEN_EXCHANGE='${{ vars.SELFCARE_HOST_FE }}/token-exchange'

          export REACT_APP_URL_API_TOKEN='${{ vars.SELFCARE_API_BE }}/api/token/token'
          export REACT_APP_URL_BACKOFFICE='${{ vars.SELFCARE_API_BE }}/backoffice/v1'
          export REACT_APP_PUBLIC_URL='/ui'
          export REACT_APP_URL_BETA='false'
          
          export REACT_APP_API_MOCK_BACKOFFICE='false'
          export REACT_APP_API_MOCK_TOKEN='false'
          
          export REACT_APP_URL_INSTITUTION_LOGO_PREFIX='${{ vars.REACT_APP_URL_STORAGE }}/institutions/'

          export REACT_APP_PAGOPA_HELP_EMAIL='assistenza@selfcare.it'
          export REACT_APP_MIXPANEL_TOKEN='${{ secrets.REACT_APP_MIXPANEL_TOKEN }}'
          export REACT_APP_ONE_TRUST_BASE_URL='${{ vars.SELFCARE_HOST_FE }}/ot/test'
          export REACT_APP_ONETRUST_DOMAIN_ID='${{ secrets.REACT_APP_ONETRUST_DOMAIN_ID }}'

          export REACT_APP_ANALYTICS_ENABLE='false'
          export REACT_APP_ANALYTICS_MOCKED='false'

          if [ "${{ needs.setup.outputs.environment }}" = "dev" ]; then
            export REACT_APP_FEATURES_FDR_ENABLED='true'
          fi

          if [ "${{ needs.setup.outputs.environment }}" = "uat" ]; then
            export REACT_APP_FEATURES_FDR_ENABLED='true'
          fi

          if [ "${{ needs.setup.outputs.environment }}" = "prod" ]; then
            export REACT_APP_FEATURES_FDR_ENABLED='false'
          fi
          
          yarn install
          yarn generate
          yarn build
          mkdir ./out
          mv ./build ./out/ui

      - name: Build And Deploy
        id: build_deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          azure_static_web_apps_api_token: ${{ secrets.AZURE_STATIC_WEB_APPS_API_TOKEN }}
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          action: 'upload'
          deployment_environment: staging
          app_location: "/out" # App source code path relative to repository root
          skip_app_build: true
          skip_api_build: true

  static_analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Lint
        run: |
          yarn install
          yarn lint

  test:
    name: Unit Test & Sonar
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set Node.js 16
        uses: actions/setup-node@v3
        with:
          node-version: 16.10.0

      - name: Unit Tests
        run: |
          yarn install
          yarn generate
          yarn test:coverage --watchAll=false

      - name: SonarCloud Scan
        uses: sonarsource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
            args: >
              -Dsonar.coverage.exclusions=**/utils/**,**/__mocks__/**,**/__tests__/**,**/api/**
